FROM php:fpm-bullseye

RUN apt-get update && apt-get install -y \
      apt-utils \
      libpq-dev \
      cron \
      libpng-dev \
      libzip-dev \
      libicu-dev \
      zip unzip \
      git && \
      docker-php-ext-install pdo_mysql && \
      docker-php-ext-install bcmath && \
      docker-php-ext-install gd && \
      docker-php-ext-install zip && \
      docker-php-ext-install pcntl && \
      docker-php-ext-configure intl && \
      docker-php-ext-install intl && \
      apt-get clean && \
      rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

RUN pecl install redis excimer && docker-php-ext-enable redis

RUN curl -sS https://getcomposer.org/installer | php -- \
    --filename=composer \
    --install-dir=/usr/local/bin


COPY ./.docker/app/crontab /crontab
RUN crontab /crontab && cron

# Install composer
# ENV COMPOSER_ALLOW_SUPERUSER=1

RUN groupadd -g 1000 www && useradd -u 1000 -ms /bin/bash -g www www
USER 1000

# RUN chmod -R 775 /var/www/storage && chmod -R 775 /var/www/bootstrap/cache

COPY ./.docker/app/php.ini /usr/local/etc/php/conf.d/php.ini

WORKDIR /var/www
