services:
    nginx:
      hostname: rubraga-nginx
      image: nginx:latest
      volumes:
        - .:/var/www
        - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        - ./.docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      depends_on:
        - app
  
    app:
      hostname: rubraga-app
      build:
        context: .
        dockerfile: ./.docker/app/dockerfile
      volumes:
        - .:/var/www
      environment:
        DB_HOST: rubraga-db
        DB_PORT: 3306
        DB_DATABASE: rubraga_dev
        DB_USERNAME: rubraga_dev
        DB_PASSWORD: 123123123
      depends_on:
        - db

    db:
      hostname: rubraga-db
      image: mysql:5.7
      volumes:
        - ./mysql:/var/lib/mysql
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: rubraga_dev
        MYSQL_USER: rubraga_dev
        MYSQL_PASSWORD: 123123123

networks:
  default:
    external: true
    name: proxy